##### Learning objectives: 

By the end of this lab, you will: 

- Use the Keras Functional API to build a simple neural network model. 

- Create an input layer, add hidden layers, and define an output layer using the

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='tensorflow')

In [2]:
# Reading data
import pandas as pd

df = pd.read_csv('kerasRegressionData.csv')
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
df.shape

(1030, 9)

In [4]:
X = df.iloc[:,:-1]
X

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360
...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28

In [5]:
X_norm = (X-X.mean())/X.std()
X_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [6]:
Y = df[['Strength']]
Y

      Strength
0        79.99
1        61.89
2        40.27
3        41.05
4        44.30
...        ...
1025     44.28
1026     31.18
1027     23.70
1028     32.77
1029     32.40

[1030 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_norm,Y,test_size=0.15,random_state=40)

In [8]:
X_train.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
486,1.012686,-0.624667,0.622086,-1.150465,1.288173,-0.449095,0.890784,-0.279597
899,-1.302962,-0.856472,1.247115,-0.026565,0.802723,0.078209,0.479190,-0.279597
323,-0.306851,-0.856472,0.697090,-1.098953,1.104037,0.191387,1.439577,0.860186
50,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,2.126612
791,0.649072,-0.856472,-0.846733,0.488555,-1.038638,0.952763,0.404354,2.126612

In [9]:
X_train.shape

(875, 8)

**Define the Input Layer**

You will define the input shape for your model. For simplicity, let's assume you are working with a dataset where each input is a vector of length 20.

In [10]:
input_layer = Input(shape=(8,))
print(input_layer)

<KerasTensor shape=(None, 8), dtype=float32, sparse=False, name=keras_tensor>

**Add Hidden Layers**

Next, you will add a couple of hidden layers to your model. Hidden layers help the model learn complex patterns in the data.

In [11]:
hidden_layer1 = Dense(60, activation='relu')(input_layer)
hidden_layer2 = Dense(50, activation='relu')(hidden_layer1)

**Define the Output Layer**

Finally, you will define the output layer. Suppose you are working on a binary classification problem, so the output layer will have one unit with a sigmoid activation function.

In [12]:
output_layer = Dense(1,activation='linear')(hidden_layer2)

**Creating the Model**

**Explanation:**

`Model(inputs=input_layer, outputs=output_layer)` creates a Keras model that connects the input layer to the output layer through the hidden layers. 

`model.summary()` provides a summary of the model, showing the layers, their shapes, and the number of parameters. This helps you interpret the model architecture.

In [13]:
model = Model(inputs=input_layer, outputs=output_layer)
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 60)             │           540 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 50)             │         3,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,641 (14.22 KB)

 Trainable params: 3,641 (14.22 KB)

 Non-trainable params: 0 (0.00 B)

**Compile the Model**

Before training the model, you need to compile it. You will specify the loss function, optimizer, and evaluation metrics.

In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

`optimizer='adam'` specifies the Adam optimizer, a popular choice for training neural networks. 

`loss='binary_crossentropy'` specifies the loss function for binary classification problems. 

`metrics=['accuracy']` instructs Keras to evaluate the model using accuracy during training. 

**Train the Model**

You can now train the model using training data. For this example, let's assume `X_train` is your training input data and `y_train` is the corresponding label.

In [21]:
model.fit(X_train, Y_train, epochs=100, verbose=1, validation_data=(X_test, Y_test))

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -551.9003 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.0000e+00 - loss: -547.4419 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.0000e+00 - loss: -553.9398 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -548.4506 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -556.0795 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -541.7227 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.0000e+00 - loss: -557.2491 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.0000e+00 - loss: -547.5562 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.0000e+00 - loss: -546.6948 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -553.4175 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.0000e+00 - loss: -537.8496 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.0000e+00 - loss: -556.7582 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 13/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.0000e+00 - loss: -553.9388 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 14/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.0000e+00 - loss: -555.9456 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 15/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.0000e+00 - loss: -550.4126 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 16/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.0000e+00 - loss: -558.5700 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 17/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.0000e+00 - loss: -538.6412 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 18/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.0000e+00 - loss: -551.5280 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 19/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.0000e+00 - loss: -554.7437 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 20/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.0000e+00 - loss: -553.8126 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 21/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.0000e+00 - loss: -560.9583 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 22/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.0000e+00 - loss: -543.9113 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 23/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.0000e+00 - loss: -545.3862 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 24/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.0000e+00 - loss: -551.1294 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 25/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -553.5239 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 26/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -554.8286 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 27/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.0000e+00 - loss: -550.6589 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 28/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -546.9681 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 29/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.0000e+00 - loss: -543.7139 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 30/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.0000e+00 - loss: -570.1090 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 31/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.0000e+00 - loss: -558.7623 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 32/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.0000e+00 - loss: -541.6640 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 33/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.0000e+00 - loss: -548.6437 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 34/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.0000e+00 - loss: -551.1522 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 35/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.0000e+00 - loss: -542.0572 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 36/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.0000e+00 - loss: -545.8521 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 37/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.0000e+00 - loss: -566.6616 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 38/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.0000e+00 - loss: -533.1003 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 39/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -545.5220 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 40/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -537.4323 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 41/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -547.2223 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 42/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -543.5751 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 43/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -545.6973 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 44/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -554.0298 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 45/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -557.6776 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 46/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -551.3004 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 47/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -551.1994 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 48/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.0000e+00 - loss: -564.0039 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 49/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -560.3727 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 50/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -554.3209 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 51/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -555.3544 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 52/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.0000e+00 - loss: -549.0369 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 53/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -550.7695 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 54/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.0000e+00 - loss: -546.9212 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 55/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.0000e+00 - loss: -551.3337 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 56/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.0000e+00 - loss: -548.3785 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 57/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -553.8991 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 58/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.0000e+00 - loss: -551.5664 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 59/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -553.7306 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 60/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.0000e+00 - loss: -559.1972 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 61/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -569.1253 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 62/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -566.4707 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 63/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.0000e+00 - loss: -542.4256 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 64/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -553.3851 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 65/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.0000e+00 - loss: -563.5029 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 66/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -553.4409 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 67/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -547.4979 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 68/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -564.5426 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 69/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -551.4624 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 70/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.0000e+00 - loss: -540.6124 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 71/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -532.5471 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 72/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.0000e+00 - loss: -549.2926 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 73/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.0000e+00 - loss: -556.9115 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 74/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -558.7149 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 75/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -545.8773 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 76/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.0000e+00 - loss: -541.2308 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 77/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.0000e+00 - loss: -559.5710 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 78/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.0000e+00 - loss: -545.9984 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 79/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.0000e+00 - loss: -550.2055 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 80/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.0000e+00 - loss: -564.0820 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 81/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.0000e+00 - loss: -568.6978 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 82/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -559.5928 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 83/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.0000e+00 - loss: -547.4562 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 84/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.0000e+00 - loss: -565.4606 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 85/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.0000e+00 - loss: -545.3745 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 86/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.0000e+00 - loss: -566.6177 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 87/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.0000e+00 - loss: -557.2626 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 88/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -550.6596 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 89/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.0000e+00 - loss: -540.9410 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 90/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.0000e+00 - loss: -558.9448 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 91/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.0000e+00 - loss: -555.9806 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 92/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.0000e+00 - loss: -551.0714 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 93/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.0000e+00 - loss: -549.9798 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 94/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -540.4951 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 95/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.0000e+00 - loss: -558.1796 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 96/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.0000e+00 - loss: -538.4844 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 97/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.0000e+00 - loss: -557.5705 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 98/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.0000e+00 - loss: -546.6560 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 99/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -547.5197 - val_accuracy: 0.0000e+00 - val_loss: -571.4368
Epoch 100/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: -560.3221 - val_accuracy: 0.0000e+00 - val_loss: -571.4368

**Step 8: Evaluate the Model**

After training, you can evaluate the model on test data to see how well it performs.

In [22]:
loss, accuracy = model.evaluate(X_test, Y_test)
print(loss, accuracy)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -583.8624
-571.436767578125 0.0

In [17]:
prediction = model.predict(X_test)
print(prediction[:5])

print(Y_test[:5])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[[1.7650524]
 [1.2591697]
 [1.5337762]
 [1.3998815]
 [1.4235972]]
     Strength
808     11.47
281     32.66
243     40.86
589     31.90
283     44.21

### Dropout and Batch Normalization

Before we proceed with the practice exercise, let's briefly discuss two important techniques often used to improve the performance of neural networks: **Dropout Layers** and **Batch Normalization**.

#### Dropout Layers

Dropout is a regularization technique that helps prevent overfitting in neural networks. During training, Dropout randomly sets a fraction of input units to zero at each update cycle. This prevents the model from becoming overly reliant on any specific neurons, which encourages the network to learn more robust features that generalize better to unseen data.

**Key points:**
- Dropout is only applied during training, not during inference.
- The dropout rate is a hyperparameter that determines the fraction of neurons to drop.


#### Batch Normalization

Batch Normalization is a technique used to improve the training stability and speed of neural networks. It normalizes the output of a previous layer by re-centering and re-scaling the data, which helps in stabilizing the learning process. By reducing the internal covariate shift (the changes in the distribution of layer inputs), batch normalization allows the model to use higher learning rates, which often speeds up convergence.

**Key Points:**

- Batch normalization works by normalizing the inputs to each layer to have a mean of zero and a variance of one.
- It is applied during both training and inference, although its behavior varies slightly between the two phases.
- Batch normalization layers also introduce two learnable parameters that allow the model to scale and - shift the normalized output, which helps in restoring the model's representational power.

**Example of adding a Dropout layer in Keras:**

In [30]:
from tensorflow.keras.layers import Dropout, Dense, Input
from tensorflow.keras.models import Model

# defining the input layer
input_layer = Input(shape=(8,))

# adding a hidden layer
hidden_layer = Dense(64, activation='relu')(input_layer)

# adding a Dropout layer
dropout_layer = Dropout(rate=0.5)(hidden_layer)

# adding another hidden layer after the Dropout
hidden_layer2 = Dense(64, activation='relu')(dropout_layer)

# defining the output layer
output_layer = Dense(1, activation='sigmoid')(hidden_layer2)

# creating the model
model = Model(inputs=input_layer, outputs=output_layer)

# summary of the model
model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,801 (18.75 KB)

 Trainable params: 4,801 (18.75 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
# compiling the model

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, Y_train, epochs=100, verbose=1, validation_data=(X_test, Y_test))

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0000e+00 - loss: -0.5994 - val_accuracy: 0.0000e+00 - val_loss: -59.4831
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -81.8034 - val_accuracy: 0.0000e+00 - val_loss: -191.6401
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -237.2204 - val_accuracy: 0.0000e+00 - val_loss: -471.3502
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -572.4825 - val_accuracy: 0.0000e+00 - val_loss: -1002.9686
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1129.6152 - val_accuracy: 0.0000e+00 - val_loss: -1893.2682
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -2193.2173 - val_accuracy: 0.0000e+00 - val_loss: -3295.9258
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -3685.3691 - val_accuracy: 0.0000e+00 - val_loss: -5333.7236
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -5651.6299 - val_accuracy: 0.0000e+00 - val_loss: -8196.9336
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -8853.8135 - val_accuracy: 0.0000e+00 - val_loss: -11963.8311
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.0000e+00 - loss: -13034.8086 - val_accuracy: 0.0000e+00 - val_loss: -16786.3008
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.0000e+00 - loss: -16610.2090 - val_accuracy: 0.0000e+00 - val_loss: -22703.1387
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.0000e+00 - loss: -23466.4688 - val_accuracy: 0.0000e+00 - val_loss: -30160.1289
Epoch 13/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.0000e+00 - loss: -31165.4453 - val_accuracy: 0.0000e+00 - val_loss: -38969.2070
Epoch 14/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.0000e+00 - loss: -41415.8867 - val_accuracy: 0.0000e+00 - val_loss: -49525.4570
Epoch 15/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -50373.3086 - val_accuracy: 0.0000e+00 - val_loss: -61802.4922
Epoch 16/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -61830.3359 - val_accuracy: 0.0000e+00 - val_loss: -75815.4141
Epoch 17/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: -78645.2812 - val_accuracy: 0.0000e+00 - val_loss: -92426.8672
Epoch 18/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -93783.8281 - val_accuracy: 0.0000e+00 - val_loss: -110524.8281
Epoch 19/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.0000e+00 - loss: -108574.1094 - val_accuracy: 0.0000e+00 - val_loss: -131113.3750
Epoch 20/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -130040.5938 - val_accuracy: 0.0000e+00 - val_loss: -154322.9688
Epoch 21/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -157951.9688 - val_accuracy: 0.0000e+00 - val_loss: -180141.7344
Epoch 22/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -189689.2500 - val_accuracy: 0.0000e+00 - val_loss: -207922.1875
Epoch 23/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -200566.1250 - val_accuracy: 0.0000e+00 - val_loss: -238907.7344
Epoch 24/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -223268.2031 - val_accuracy: 0.0000e+00 - val_loss: -272654.5312
Epoch 25/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -282350.5312 - val_accuracy: 0.0000e+00 - val_loss: -309929.5938
Epoch 26/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -303563.1875 - val_accuracy: 0.0000e+00 - val_loss: -349330.0625
Epoch 27/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -333830.4688 - val_accuracy: 0.0000e+00 - val_loss: -392263.5938
Epoch 28/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -413221.5312 - val_accuracy: 0.0000e+00 - val_loss: -439087.0625
Epoch 29/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -427970.4062 - val_accuracy: 0.0000e+00 - val_loss: -487366.0938
Epoch 30/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -495313.5625 - val_accuracy: 0.0000e+00 - val_loss: -539693.5000
Epoch 31/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -538160.8125 - val_accuracy: 0.0000e+00 - val_loss: -594495.8750
Epoch 32/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -578470.0000 - val_accuracy: 0.0000e+00 - val_loss: -653751.8125
Epoch 33/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -657808.9375 - val_accuracy: 0.0000e+00 - val_loss: -716370.7500
Epoch 34/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.0000e+00 - loss: -728889.6875 - val_accuracy: 0.0000e+00 - val_loss: -783672.6875
Epoch 35/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -766877.6875 - val_accuracy: 0.0000e+00 - val_loss: -852167.5625
Epoch 36/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -849464.1875 - val_accuracy: 0.0000e+00 - val_loss: -926373.6875
Epoch 37/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -888160.8125 - val_accuracy: 0.0000e+00 - val_loss: -1001873.2500
Epoch 38/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: -983121.3125 - val_accuracy: 0.0000e+00 - val_loss: -1083670.7500
Epoch 39/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1064393.8750 - val_accuracy: 0.0000e+00 - val_loss: -1169027.7500
Epoch 40/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1119026.5000 - val_accuracy: 0.0000e+00 - val_loss: -1257159.1250
Epoch 41/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1247285.0000 - val_accuracy: 0.0000e+00 - val_loss: -1351138.7500
Epoch 42/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1335477.0000 - val_accuracy: 0.0000e+00 - val_loss: -1446744.1250
Epoch 43/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1412205.2500 - val_accuracy: 0.0000e+00 - val_loss: -1547558.2500
Epoch 44/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.0000e+00 - loss: -1484197.2500 - val_accuracy: 0.0000e+00 - val_loss: -1654386.0000
Epoch 45/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1637619.0000 - val_accuracy: 0.0000e+00 - val_loss: -1764338.7500
Epoch 46/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1780454.0000 - val_accuracy: 0.0000e+00 - val_loss: -1879140.3750
Epoch 47/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -1860056.2500 - val_accuracy: 0.0000e+00 - val_loss: -1995776.8750
Epoch 48/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.0000e+00 - loss: -1900625.5000 - val_accuracy: 0.0000e+00 - val_loss: -2116190.7500
Epoch 49/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -2043951.5000 - val_accuracy: 0.0000e+00 - val_loss: -2244658.0000
Epoch 50/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -2141898.2500 - val_accuracy: 0.0000e+00 - val_loss: -2375733.7500
Epoch 51/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.0000e+00 - loss: -2378522.5000 - val_accuracy: 0.0000e+00 - val_loss: -2512415.5000
Epoch 52/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -2444904.7500 - val_accuracy: 0.0000e+00 - val_loss: -2651169.5000
Epoch 53/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.0000e+00 - loss: -2598703.0000 - val_accuracy: 0.0000e+00 - val_loss: -2795233.0000
Epoch 54/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -2716279.0000 - val_accuracy: 0.0000e+00 - val_loss: -2944872.0000
Epoch 55/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -2971355.7500 - val_accuracy: 0.0000e+00 - val_loss: -3099163.2500
Epoch 56/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.0000e+00 - loss: -3006236.7500 - val_accuracy: 0.0000e+00 - val_loss: -3257466.5000
Epoch 57/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.0000e+00 - loss: -3140823.7500 - val_accuracy: 0.0000e+00 - val_loss: -3418023.2500
Epoch 58/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -3502772.7500 - val_accuracy: 0.0000e+00 - val_loss: -3588609.7500
Epoch 59/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.0000e+00 - loss: -3477898.5000 - val_accuracy: 0.0000e+00 - val_loss: -3759111.7500
Epoch 60/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -3778880.5000 - val_accuracy: 0.0000e+00 - val_loss: -3937881.5000
Epoch 61/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -3781284.0000 - val_accuracy: 0.0000e+00 - val_loss: -4117639.7500
Epoch 62/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.0000e+00 - loss: -3893858.5000 - val_accuracy: 0.0000e+00 - val_loss: -4299034.5000
Epoch 63/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.0000e+00 - loss: -4058312.2500 - val_accuracy: 0.0000e+00 - val_loss: -4490492.5000
Epoch 64/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -4346925.5000 - val_accuracy: 0.0000e+00 - val_loss: -4689814.5000
Epoch 65/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -4633548.5000 - val_accuracy: 0.0000e+00 - val_loss: -4891053.0000
Epoch 66/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -4694298.0000 - val_accuracy: 0.0000e+00 - val_loss: -5096301.5000
Epoch 67/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -5262353.0000 - val_accuracy: 0.0000e+00 - val_loss: -5309181.0000
Epoch 68/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -5116026.0000 - val_accuracy: 0.0000e+00 - val_loss: -5527864.5000
Epoch 69/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -5103073.0000 - val_accuracy: 0.0000e+00 - val_loss: -5748977.0000
Epoch 70/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.0000e+00 - loss: -6095662.5000 - val_accuracy: 0.0000e+00 - val_loss: -5983779.0000
Epoch 71/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -5754737.5000 - val_accuracy: 0.0000e+00 - val_loss: -6210228.5000
Epoch 72/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -6126467.0000 - val_accuracy: 0.0000e+00 - val_loss: -6449908.0000
Epoch 73/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.0000e+00 - loss: -6303516.5000 - val_accuracy: 0.0000e+00 - val_loss: -6694888.0000
Epoch 74/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -6535644.5000 - val_accuracy: 0.0000e+00 - val_loss: -6939897.5000
Epoch 75/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.0000e+00 - loss: -6698866.5000 - val_accuracy: 0.0000e+00 - val_loss: -7194720.5000
Epoch 76/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -6996071.5000 - val_accuracy: 0.0000e+00 - val_loss: -7455568.0000
Epoch 77/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.0000e+00 - loss: -7565072.0000 - val_accuracy: 0.0000e+00 - val_loss: -7722786.5000
Epoch 78/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -7146515.5000 - val_accuracy: 0.0000e+00 - val_loss: -7987155.5000
Epoch 79/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.0000e+00 - loss: -8056432.0000 - val_accuracy: 0.0000e+00 - val_loss: -8264111.0000
Epoch 80/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -7694712.0000 - val_accuracy: 0.0000e+00 - val_loss: -8535244.0000
Epoch 81/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -8545911.0000 - val_accuracy: 0.0000e+00 - val_loss: -8820223.0000
Epoch 82/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -8265404.0000 - val_accuracy: 0.0000e+00 - val_loss: -9104222.0000
Epoch 83/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -8766751.0000 - val_accuracy: 0.0000e+00 - val_loss: -9400572.0000
Epoch 84/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -9594608.0000 - val_accuracy: 0.0000e+00 - val_loss: -9704275.0000
Epoch 85/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -9509113.0000 - val_accuracy: 0.0000e+00 - val_loss: -10009108.0000
Epoch 86/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -9646457.0000 - val_accuracy: 0.0000e+00 - val_loss: -10316641.0000
Epoch 87/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -9582941.0000 - val_accuracy: 0.0000e+00 - val_loss: -10641658.0000
Epoch 88/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -10752853.0000 - val_accuracy: 0.0000e+00 - val_loss: -10971694.0000
Epoch 89/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -10690599.0000 - val_accuracy: 0.0000e+00 - val_loss: -11300544.0000
Epoch 90/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -11092529.0000 - val_accuracy: 0.0000e+00 - val_loss: -11637413.0000
Epoch 91/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -11315036.0000 - val_accuracy: 0.0000e+00 - val_loss: -11972450.0000
Epoch 92/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: -11649746.0000 - val_accuracy: 0.0000e+00 - val_loss: -12314039.0000
Epoch 93/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -12035086.0000 - val_accuracy: 0.0000e+00 - val_loss: -12664738.0000
Epoch 94/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -12193163.0000 - val_accuracy: 0.0000e+00 - val_loss: -13021092.0000
Epoch 95/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -12801626.0000 - val_accuracy: 0.0000e+00 - val_loss: -13378022.0000
Epoch 96/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.0000e+00 - loss: -12606174.0000 - val_accuracy: 0.0000e+00 - val_loss: -13742798.0000
Epoch 97/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -12739678.0000 - val_accuracy: 0.0000e+00 - val_loss: -14112857.0000
Epoch 98/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.0000e+00 - loss: -14064607.0000 - val_accuracy: 0.0000e+00 - val_loss: -14493159.0000
Epoch 99/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: -14260610.0000 - val_accuracy: 0.0000e+00 - val_loss: -14879523.0000
Epoch 100/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0000e+00 - loss: -14553672.0000 - val_accuracy: 0.0000e+00 - val_loss: -15263757.0000

**Example of adding Batch Normalization in Keras:**

In [25]:
from tensorflow.keras.layers import BatchNormalization, Dense, Input
from tensorflow.keras.models import Model

# Define the input layer
input_layer = Input(shape=(20,))

# adding a hidden layer
hidden_layer = Dense(64, activation='relu')(input_layer)

# adding a BatchNormalization layer
batch_norm_layer = BatchNormalization()(hidden_layer)

# adding another hidden layer after batch normalization
hidden_layer2 = Dense(64, activation='relu')(batch_norm_layer)

# defining the output layer
output_layer = Dense(1, activation='sigmoid')(hidden_layer2)

# creating the model
model = Model(inputs=input_layer, outputs=output_layer)

# summary of the model
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         1,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,825 (22.75 KB)

 Trainable params: 5,697 (22.25 KB)

 Non-trainable params: 128 (512.00 B)